"use client";

import { FormEvent, useMemo, useState } from "react";
import { RealAuth } from "./real-auth";

type Project={id:number;date:string;title:string;description:string;image:string;assigned?:string};
type Proposal={id:number;projectId:number;date:string;student:string;title:string;description:string};
const initialProjects:Project[]=[
 {id:1,date:"04 Aug 2026",title:"Digitise our stocktake",description:"Help a neighbourhood bakery replace paper stock counts with a simple mobile-friendly workflow.",image:"Inventory shelves and daily count sheets",assigned:"Aisha Rahman"},
 {id:2,date:"29 Jul 2026",title:"Refresh our customer website",description:"Create a clear, welcoming website that helps families discover our enrichment programmes.",image:"Current homepage and brand photographs"},
 {id:3,date:"18 Jul 2026",title:"Reduce appointment no-shows",description:"Explore a lightweight reminder process for a small physiotherapy clinic.",image:"Existing appointment reminder screens"}
];
const initialProposals:Proposal[]=[
 {id:1,projectId:1,date:"06 Aug 2026",student:"Aisha Rahman",title:"Smart Stock, Simple Shift",description:"A four-week discovery and prototype sprint focused on fast daily counts, low-stock alerts and a clear handover guide."},
 {id:2,projectId:1,date:"07 Aug 2026",student:"Marcus Tan",title:"Bakery Inventory Companion",description:"A responsive inventory prototype tested with counter staff, including reusable product templates and weekly summaries."},
 {id:3,projectId:2,date:"01 Aug 2026",student:"Aisha Rahman",title:"A warmer digital front door",description:"Content restructuring, accessible visual design and a responsive prototype for parents browsing on mobile."}
];
const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,"");
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
async function createSupabaseProject(title:string,description:string){const token=sessionStorage.getItem("sme-access-token");if(!token)throw new Error("Please sign in again before creating a project.");let ownerId=sessionStorage.getItem("sme-user-id");if(!ownerId){const userResponse=await fetch(`${supabaseUrl}/auth/v1/user`,{headers:{apikey:supabaseKey??"",Authorization:`Bearer ${token}`}});const user=await userResponse.json();if(!userResponse.ok||!user.id)throw new Error("Your session could not be verified. Please sign in again.");ownerId=user.id;sessionStorage.setItem("sme-user-id",ownerId)}const response=await fetch(`${supabaseUrl}/rest/v1/projects`,{method:"POST",headers:{apikey:supabaseKey??"",Authorization:`Bearer ${token}`,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({owner_id:ownerId,title,description,image_reference:null})});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||"The project could not be saved to Supabase.");return data?.[0];}
type View="login"|"signup"|"verified"|"forgot"|"reset"|"sme"|"project"|"review"|"student"|"search"|"submit";

export default function Home(){
 const [view,setView]=useState<View>("login"),[role,setRole]=useState<"sme"|"student">("sme"),[projects,setProjects]=useState(initialProjects),[proposals,setProposals]=useState(initialProposals),[projectId,setProjectId]=useState(1),[proposalId,setProposalId]=useState(1),[query,setQuery]=useState("");
 const project=projects.find(p=>p.id===projectId)??projects[0], proposal=proposals.find(p=>p.id===proposalId)??proposals[0];
 const projectProposals=proposals.filter(p=>p.projectId===project.id);
 const results=useMemo(()=>projects.filter(p=>(p.title+" "+p.description).toLowerCase().includes(query.toLowerCase())),[projects,query]);
 const go=(next:View)=>{setView(next);window.scrollTo({top:0,behavior:"smooth"})};
 const assign=(p:Proposal)=>{setProjects(items=>items.map(x=>x.id===p.projectId?{...x,assigned:p.student}:x));setProposalId(p.id)};
 const enter=(r:"sme"|"student")=>{setRole(r);go(r==="sme"?"sme":"student")};
 const nav=<header className="top"><button className="brand" onClick={()=>go(role==="sme"?"sme":"student")}><span>SP</span><b>SME Projects</b></button><nav><button onClick={()=>go(role==="sme"?"sme":"student")}>My workspace</button>{role==="student"&&<button onClick={()=>go("search")}>Find projects</button>}<button className="avatar" onClick={()=>go("login")}>DL</button></nav></header>;
 if(["login","signup","verified","forgot","reset"].includes(view)) return <RealAuth view={view} go={go} enter={enter}/>;
 return <><div className="accent"/>{nav}<main className="shell">
  {view==="sme"&&<><Hero eyebrow="SME workspace" title="Turn business challenges into student-led progress." text="Share a real operational need, review thoughtful proposals and choose the right student team." action="Create a project" onAction={()=>{setProjectId(0);go("project")}}/><SectionTitle title="Your projects" text={`${projects.length} active briefs`}/><ProjectTable projects={projects} proposals={proposals} open={id=>{setProjectId(id);go("project")}}/></>}
  {view==="student"&&<><Hero eyebrow="Student workspace" title="Build experience that matters." text="Track your proposals and see where your ideas are making a difference." action="Explore projects" onAction={()=>go("search")}/><SectionTitle title="Your proposals" text="Submitted as Aisha Rahman"/><div className="table"><table><thead><tr><th>Date created</th><th>Project</th><th>Proposal</th><th>Status</th></tr></thead><tbody>{proposals.filter(p=>p.student==="Aisha Rahman").map(p=><tr key={p.id}><td>{p.date}</td><td>{projects.find(x=>x.id===p.projectId)?.title}</td><td><button className="link" onClick={()=>{setProjectId(p.projectId);setProposalId(p.id);go("submit")}}>{p.title}</button></td><td><Status yes={projects.find(x=>x.id===p.projectId)?.assigned===p.student}/></td></tr>)}</tbody></table></div></>}
  {view==="search"&&<><PageHead back={()=>go("student")} eyebrow="Opportunity board" title="Find a project worth solving"/><label className="search"><span>Search by project title or description</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try ‘website’ or ‘inventory’"/></label><ProjectTable projects={results} proposals={proposals} open={id=>{setProjectId(id);go("submit")}}/></>}
  {view==="project"&&<ProjectDetail project={projectId?project:undefined} proposals={projectProposals} back={()=>go("sme")} save={async(title,description)=>{try{if(projectId)setProjects(x=>x.map(p=>p.id===projectId?{...p,title,description}:p));else{await createSupabaseProject(title,description);const id=Date.now();setProjects(x=>[{id,date:"08 Aug 2026",title,description,image:"No reference added"},...x]);setProjectId(id)};go("sme")}catch(error){window.alert(error instanceof Error?error.message:"Unable to save project.")}}} review={id=>{setProposalId(id);go("review")}} assign={assign}/>}
  {view==="review"&&<Review proposal={proposal} project={project} back={()=>go("project")} assign={()=>assign(proposal)}/>}
  {view==="submit"&&<Submit project={project} proposal={proposals.find(p=>p.projectId===project.id&&p.student==="Aisha Rahman")} back={()=>go(view==="submit"?"student":"search")} save={(title,description)=>{setProposals(x=>{const old=x.find(p=>p.projectId===project.id&&p.student==="Aisha Rahman");return old?x.map(p=>p.id===old.id?{...p,title,description}:p):[...x,{id:Date.now(),projectId:project.id,date:"08 Aug 2026",student:"Aisha Rahman",title,description}]});go("student")}}/>}
 </main><footer>SME Projects <span>Connecting practical problems with emerging talent.</span></footer></>;
}

function Auth({view,go,enter}:{view:View;go:(v:View)=>void;enter:(r:"sme"|"student")=>void}){const [kind,setKind]=useState<"sme"|"student">("sme");const submit=(e:FormEvent)=>{e.preventDefault();view==="signup"?go("verified"):view==="forgot"?go("reset"):view==="reset"?go("login"):enter(kind)};const copy=view==="signup"?["Create your account","Join a community turning real challenges into practical learning."]:view==="forgot"?["Forgot your password?","Enter your email and we’ll send a secure reset link."]:view==="reset"?["Choose a new password","Use at least eight characters for your new password."]:view==="verified"?["Email verified","Your account is enabled. You can now sign in."]:["Make progress, together.","A focused space for SMEs and students to solve meaningful business challenges."];return <main className="auth"><section className="auth-story"><div className="brand light"><span>SP</span><b>SME Projects</b></div><p className="eyebrow">Singapore’s applied learning network</p><h1>{copy[0]}</h1><p>{copy[1]}</p><div className="story-card"><b>Real briefs. Fresh thinking.</b><span>One shared workspace from first idea to chosen proposal.</span></div></section><section className="auth-form"><div className="panel">{view==="verified"?<><div className="verified">✓</div><h2>Email verified</h2><p>Your account is ready. Continue to the login page.</p><button className="primary" onClick={()=>go("login")}>Continue to login</button></>:<><p className="eyebrow">Welcome</p><h2>{copy[0]}</h2><form onSubmit={submit}>{view==="signup"&&<><label>User ID<input required minLength={3} placeholder="desmond.ling"/></label><label>Account type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="sme">SME Owner</option><option value="student">Student</option></select></label></>} {view==="login"&&<div className="role"><button type="button" className={kind==="sme"?"active":""} onClick={()=>setKind("sme")}>SME Owner</button><button type="button" className={kind==="student"?"active":""} onClick={()=>setKind("student")}>Student</button></div>}<label>Email address<input required type="email" placeholder="you@company.com"/></label>{view!=="forgot"&&<label>{view==="reset"?"New password":"Password"}<input required type="password" minLength={8} placeholder="At least 8 characters"/></label>}<button className="primary" type="submit">{view==="signup"?"Create account":view==="forgot"?"Send reset link":view==="reset"?"Reset password":"Sign in"}</button></form><div className="auth-links">{view==="login"?<><button onClick={()=>go("forgot")}>Forgot password?</button><span>New here? <button onClick={()=>go("signup")}>Create an account</button></span></>:<button onClick={()=>go("login")}>Back to login</button>}</div></>}</div></section></main>}
function Hero(p:{eyebrow:string;title:string;text:string;action:string;onAction:()=>void}){return <section className="hero"><div><p className="eyebrow">{p.eyebrow}</p><h1>{p.title}</h1><p>{p.text}</p></div><button className="primary" onClick={p.onAction}>＋ {p.action}</button></section>}
function SectionTitle({title,text}:{title:string;text:string}){return <div className="section-title"><h2>{title}</h2><span>{text}</span></div>}
function Status({yes}:{yes:boolean}){return <span className={yes?"status assigned":"status"}>{yes?"Assigned":"Under review"}</span>}
function ProjectTable({projects,proposals,open}:{projects:Project[];proposals:Proposal[];open:(id:number)=>void}){return <div className="table"><table><thead><tr><th>Date created</th><th>Project</th><th>Proposals</th><th>Assigned to</th></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td>{p.date}</td><td><button className="link" onClick={()=>open(p.id)}>{p.title}</button><small>{p.description}</small></td><td>{proposals.filter(x=>x.projectId===p.id).length}</td><td>{p.assigned??<span className="muted">Not assigned</span>}</td></tr>)}</tbody></table>{!projects.length&&<p className="empty">No matching projects found.</p>}</div>}
function PageHead({back,eyebrow,title}:{back:()=>void;eyebrow:string;title:string}){return <div className="page-head"><button onClick={back}>← Back</button><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>}
function ProjectDetail({project,proposals,back,save,review,assign}:{project?:Project;proposals:Proposal[];back:()=>void;save:(a:string,b:string)=>void;review:(id:number)=>void;assign:(p:Proposal)=>void}){const [title,setTitle]=useState(project?.title??""),[description,setDescription]=useState(project?.description??"");return <><PageHead back={back} eyebrow={project?"Project details":"New project"} title={project?.title??"Create a clear project brief"}/><div className="card form-card"><label>Project title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={160}/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={5} maxLength={5000}/></label><label>Image reference<input defaultValue={project?.image??""} placeholder="Paste a link or describe the reference"/></label><button className="primary" disabled={title.trim().length<3||description.trim().length<10} onClick={()=>save(title,description)}>Save project</button></div>{project&&<><SectionTitle title="Student proposals" text={`${proposals.length} received`}/><div className="table"><table><thead><tr><th>Student</th><th>Proposal</th><th>Assignment</th></tr></thead><tbody>{proposals.map(p=><tr key={p.id}><td>{p.student}</td><td><button className="link" onClick={()=>review(p.id)}>{p.title} ↗</button></td><td><button className={project.assigned===p.student?"assigned-button":"outline"} onClick={()=>assign(p)}>{project.assigned===p.student?"Assigned":"Assign"}</button></td></tr>)}</tbody></table></div></>}</>}
function Review({proposal,project,back,assign}:{proposal:Proposal;project:Project;back:()=>void;assign:()=>void}){return <><PageHead back={back} eyebrow="Review proposal" title={proposal.title}/><div className="detail-grid"><article className="card"><span>Date submitted</span><b>{proposal.date}</b><span>Student</span><b>{proposal.student}</b><span>Project</span><b>{project.title}</b></article><article className="card prose"><h2>Approach</h2><p>{proposal.description}</p><button className="primary" onClick={assign}>{project.assigned===proposal.student?"Assigned to this student":"Assign project"}</button></article></div></>}
function Submit({project,proposal,back,save}:{project:Project;proposal?:Proposal;back:()=>void;save:(a:string,b:string)=>void}){const [title,setTitle]=useState(proposal?.title??""),[description,setDescription]=useState(proposal?.description??"");return <><PageHead back={back} eyebrow="Proposal workspace" title={project.title}/><div className="detail-grid"><article className="card prose"><span className="eyebrow">The brief</span><h2>{project.title}</h2><p>{project.description}</p><small>Image reference: {project.image}</small></article><article className="card form-card"><h2>{proposal?"Your proposal":"Submit a proposal"}</h2><label>Proposal title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={160}/></label><label>Description<textarea rows={7} value={description} onChange={e=>setDescription(e.target.value)} maxLength={5000}/></label><button className="primary" disabled={title.trim().length<3||description.trim().length<10} onClick={()=>save(title,description)}>{proposal?"Save changes":"Submit proposal"}</button></article></div></>}
